AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend for Portfolio Application (HTTP API)

Parameters:
  BlogsTable:
    Type: String
    Default: BlogsTable
  CommentsTable:
    Type: String
    Default: BlogCommentsTable
  SkillsTable:
    Type: String
    Default: SkillsTable
  ProjectsTable:
    Type: String
    Default: ProjectsTable
  ProfileTable:
    Type: String
    Default: ProfileTable
  UsersTable:
    Type: String
    Default: UsersTable

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.10
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
    Environment:
      Variables:
        BLOG_TABLE: !Ref BlogsTable
        COMMENTS_TABLE: !Ref CommentsTable
        SKILL_TABLE: !Ref SkillsTable
        PROJECTS_TABLE: !Ref ProjectsTable
        PROFILE_TABLE: !Ref ProfileTable
        USERS_TABLE: !Ref UsersTable
        PASSKEY: Kartik@3165
        JWT_SECRET: a33yiINSTHr4w9kpasLKPJYja2v8QZrvWWYC1JoLWr6wGjKPaD1q2JHtMoZqduFh
        R2_ACCOUNT_ID: 976dcfdf7586d24be34b8392323d28b8
        R2_ACCESS_KEY_ID: 17a69a03752ba1594849d37299b6e4c8
        R2_SECRET_ACCESS_KEY: a6d9f322bd581f5110f630170bacb03766004bdd3b88b5b08102d27f8a06de72
        R2_BUCKET_NAME: portfolio-bucket
        R2_PUBLIC_BASE_URL: https://image.kanbs.me

Resources:
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins:
          - https://admin.kanbs.me
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - content-type
          - authorization
        AllowCredentials: true

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BlogsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfileTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"